name: KitsPro
version: 1.0.0
api: [5.0.0]
main: Terpz710\KitsPro\Main
author: Terpz710
description: A kit system with GUI for PocketMine-MP
permissions:
  kitspro.kit:
    description: Allows players to use the /kit command.
    default: true
